import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useEffect, useMemo, useRef, useState } from 'react'
// import { useStartPeerSession } from "../hooks/startUserPeerConnection";
// import { useCreateMediaStream } from "../hooks/useCreateMediaStream";

export default function Home() {
    // const room = "room1";
    // const galleryRef = useRef();
    // const mainRef = useRef();

    // useEffect(() => {
    //   const localVideo = document.getElementById("#localVideo");
    //   const userMediaStream = useCreateMediaStream(localVideo);
    //   const { connectedUsers, shareScreen, cancelScreenSharing, isScreenShared } =
    //     useStartPeerSession(room, userMediaStream, localVideo);
    // });

    useEffect(() => {
        const navigator = window.navigator

        navigator.mediaDevices
            .getUserMedia({ audio: true, video: true })
            .then((stream) => {
                const localVideo = document.getElementById('localVideo') as HTMLVideoElement
                localVideo.srcObject = stream
                localVideo.onloadedmetadata = () => {
                    localVideo.play()
                }
            })
            .catch((err) => {
                console.log(err)
            })
    })

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <video id="localVideo" autoPlay></video>
                {/* {connectedUsers.map((user) => (
          <video key={user} id={user} autoPlay playsInline />
        ))} */}
            </main>
        </>
    )
}
